# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b260e8358ee4b27b5805909a1b895287"
name = "3dpc-extensions"
handle = "3dpc-extensions"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts, read_discounts, read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
